### ISSUE TITLE
MacOS java.util.HashMap cannot be cast to java.awt.RenderingHints

### ISSUE THREAD

**Issue by WolfgangFahl** [albfan/jmeld#14]
https://java.net/jira/browse/JIDE_OSS-11
hits this. 

Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to java.awt.RenderingHints
	at com.jidesoft.swing.JideSwingUtilities.<clinit>(JideSwingUtilities.java:1901)
	... 31 more

**Comment by albfan** [comment]
It's ok to me to stay on the edge for dependencies. Upgrade pom.xml and check if everything works. If it does provide a PR, if not we can config a profile for mac

**Comment by WolfgangFahl** [comment]
wf@jupiter:~/Documents/workspace/jmeld>git diff pom.xml 
diff --git a/pom.xml b/pom.xml
index 5cebec5..2be2f43 100644
--- a/pom.xml
+++ b/pom.xml
@@ -93,7 +93,7 @@
         <dependency>
             <groupId>com.jidesoft</groupId>
             <artifactId>jide-oss</artifactId>
-            <version>2.9.7</version>
+            <version>3.6.9</version>
         </dependency>
         <dependency>
             <groupId>org.swinglabs</groupId>

**Comment by albfan** [comment]
Thanks. As you can see I reworked it to isolate commits for issues.
