### ISSUE TITLE
Keyboard shortcuts : close tab, close all

### ISSUE THREAD

**Issue by KewlCat** [albfan/jmeld#23]
Hi

Can you please add two keyboard shortcuts ?  [Ctrl] + [W] to close the current tab and [Ctrl] + [Q] to completely close the application ?

**Comment by albfan** [comment]
Send a PR about that. It will be accepted.

If you have any problems to understand codebase feel free to ask.

On linux system `alt+f4` works for free to close app. What OS are you using? Maybe shortcuts should be OS dependant.

**Comment by KewlCat** [comment]
AFAIK Alt-F4 is caught by the window manager and not by the app. I'm not interested in trying to kill the app from the system, but to make it close gently by itself.
I have a few changes to commit, how do I attach them here ?

**Comment by albfan** [comment]
You can open a branch and send a PR. We can rebase or merge it later

**Comment by albfan** [comment]
This will be managed on #29
