### ISSUE TITLE
Compilation fails with ant, execution fails when compiled with mvn

### ISSUE THREAD

**Issue by KewlCat** [albfan/jmeld#24]
Hi

First, nope, I still haven't had the time to look at the source and add the keyboard shortcuts. That will be the second step. I'm trying to compile it first.

I took the 3.0 release archive and tried the following : 
- "ant" : fails because source is not good
- add the argument includeantruntime="false" because I don't like warnings ;-)
- change source and target to 8 in build.xml then "ant" : fails because libs are missing
- tried to download (and compile, for some) those libs but gave up after the fifth
- "mvn compile" : yay ! it downloads the missing libs
- "mvn install" : woohoo ! produces a "target/jmeld-3.0.jar" 
  So far, so good. BUT
  "java -jar jmeld-3.0.jar" fails because "no main manifest attribute"
  "java -cp jmeld-3.0.jar org.jmeld.JMeld" fails because "NoClassDefFoundError: (...)/PlasticLookandFeel"

OKAY

I feel like I'm getting closer but I'm still missing something.
What is wrong with the way I compile JMeld ? Aren't those libs supposed to land inside the produced jar ?

**Comment by albfan** [comment]
Here you have two problems. First ant is clearly outdated (need to provide deps on your own)

For maven you can use https://github.com/albfan/mvnexec as readme says ( it's really handy) or take a look at src/main/scripts. There is a script to launch jmeld, copy to root project and modify absolute paths (those are mine)

**Comment by KewlCat** [comment]
"make is outdated, use autoconf" / "autoconf is outdated, use CMake" / "CMake is outdated, use scons" / etc.
Everybody should stop doing that.
In the end, it is now impossible to compile chromium (e.g.) on more than ONE THREAD because the build system is unable to manage dependencies, something `make` could properly do from day one. Please.
</rant>

Anyway.
I have a quick and very dirty way to make `ant` work.
```shell
cd lib
wget -Ojide.jar https://repo.maven.apache.org/maven2/com/jidesoft/jide-oss/3.6.11/jide-oss-3.6.11.jar
wget -Oforms-1.0.7.jar https://repo.maven.apache.org/maven2/jgoodies/forms/1.0.5/forms-1.0.5.jar
wget -Olooks-2.2.1.jar https://repo.maven.apache.org/maven2/com/jgoodies/looks/2.2.2/looks-2.2.2.jar
wget -Oswingx-0.9.4.jar https://repo.maven.apache.org/maven2/org/swinglabs/swingx/1.6.1/swingx-1.6.1.jar
wget -Ojsr173_1.0_api.jar https://repo.maven.apache.org/maven2/javax/xml/jsr173/1.0/jsr173-1.0.jar
wget -Oswing-layout-1.0.3.jar https://repo.maven.apache.org/maven2/org/swinglabs/swing-layout/1.0.3/swing-layout-1.0.3.jar
wget -Oicu4j-4_0.jar https://repo.maven.apache.org/maven2/org/mod4j/com/ibm/icu/4.0.1/icu-4.0.1.jar
wget -Ojaxb-api.jar https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.2.11/jaxb-api-2.2.11.jar
wget -Ojaxb-core.jar https://repo.maven.apache.org/maven2/com/sun/xml/bind/jaxb-core/2.2.11/jaxb-core-2.2.11.jar
wget -Ojaxb-impl.jar https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar
wget -Oactivation.jar https://repo.maven.apache.org/maven2/javax/activation/activation/1.1.1/activation-1.1.1.jar
cp com/l2fprod/common/7.3/common-7.3.jar l2fprod-common-all.jar
```
Yes, I know, versions do not match. I'm OK to maintain a working `build.xml` script and to leave the dependencies as an exercise for the reader ;-)

**Comment by albfan** [comment]
mvn dependency:copy-dependencies would be enough. Inside target dir you
will find a directory with all dependencies

**Comment by KewlCat** [comment]
My guess is that `mvn dependency:copy-dependencies` would not rename the jar files as they are expected by the `build.xml` script, which means another round of `mv`  to rename them afterwards. Also, I intend to look for more recent versions of these libraries (if possible). JGoodies Forms, for instance, has released many more versions after 1.0.5 and I couldn't even find version 1.0.7 through maven. There's something to correct right here, I think.

**Comment by albfan** [comment]
Funny you expect maven compilation be aware of ant compilation.

See maven 3 support local repositories (as you can see on lib dir)

**Comment by KewlCat** [comment]
Yeah, I know they are disconnected ; what I was trying to say is that for the time being I'd try and have `ant` build an executable with its existing requirements. The next step is to overhaul the `build.xml` file to point to newer (and correct) versions of those libs.

**Comment by albfan** [comment]
Great. My choose is to forget about ant, but if you feel comfortable with it, consider using http://ant.apache.org/ivy/. Is exactly what you are looking for, saves you from dependency hell and work is almost done since ivy understand maven central routes.

**Comment by KewlCat** [comment]
I have no idea what "dependency hell" you're talking about, especially since you publish a rather odd wrapper ( https://github.com/albfan/jmeld/blob/master/src/main/scripts/jmeld ) which references absolute paths to your home directory's subtree.
I'd rather have "dependency hell" at compile-time and not put the burden on the users to have all these exact lib versions in their classpaths.

Anyway, my only problem was to have a working build system, and I managed to have a working build system ;-)

**Comment by albfan** [comment]
You can read about it on https://en.wikipedia.org/wiki/Dependency_hell

That script is the output from 

https://github.com/albfan/mvnexec/blob/master/mvnexec#L93. 

And was generated automatically. It is an start for an executable, not a finished script. I forget at some point to finish it, thanks for pointing out.

I'm focused on provide test suite and code coverage on several projects I maintain but I keep an eye on these PR, and hope incorporate and fix up some quirks on jmeld on next weeks.

**Comment by albfan** [comment]
Whatever this rant is about, fat jar .exe, etc should provide an executable that work. ivy is the solution for ant dependencies.
