### ISSUE TITLE
Releasing fat jar

### ISSUE THREAD

**Issue by albfan** [albfan/jmeld#53]
Allow people to use jmeld isolated

https://www.mkyong.com/maven/create-a-fat-jar-file-maven-assembly-plugin/

**Comment by WolfgangFahl** [comment]
see my pullrequest #54

**Comment by albfan** [comment]
@WolfgangFahl main objetive is an executable jar. Of course specific OS releases are welcomed. I will continue your work on https://github.com/albfan/jmeld/tree/wip/fat-jar, let me know if that is ok for you.

I forgot to push tag 3.3 to master, that work is rebased too.

**Comment by albfan** [comment]
hmm, fat-jar is there, so with exe, linux and windows are covered. Let me merge then. If someone needs a specific release for mac we can work on that later

**Comment by WolfgangFahl** [comment]
Great. I personally have some repositories where I release the exe and jar files via the git repository. You could also use github pages for that.
See http://www.bitplan.com/index.php/Com.bitplan.pom for my recent work on how to better use maven for the release process. I also have a script for handling the github pages stuff in a more automated way - please send me a personal mail if you are interested in that.

**Comment by albfan** [comment]
Fixed on c2c196d
