### ISSUE TITLE
build with jdk11

### ISSUE THREAD

**Issue by turiot** [albfan/jmeld#59]
Thanks for the maintenance of this wonderful tool, which works on jdk11.
Is it possible to add the following dependencies to pom.xml ?

        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
            <type>jar</type>
        </dependency>

**Comment by albfan** [comment]
You need to explain "why" that dependencies should be added.

By now it is a no. I will reopen if you explain why.

**Comment by turiot** [comment]
Just because the maven project doesn't build without these dependencies.

**Comment by albfan** [comment]
CI passes: https://travis-ci.org/albfan/jmeld, so is this related to jdk11?

**Comment by albfan** [comment]
Please add a profile activated by jdk and add those extra dependencies https://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Comment by albfan** [comment]
Thanks @turiot I credited you on 7e5df19f4e73e047488b6f7591908b855fdde151 and restore CI
