### ISSUE TITLE
Flat Jar

### ISSUE THREAD

**Issue by thevpc** [albfan/jmeld#70]
Thank you for this amazing piece of work. I love Meld and it was my great joy to discover, very recently actually, that you are rewriting it in java.
My concern is only about the release package formats. I see you are using assembly plugin "jar-with-dependencies", could you please continue releasing a plain/flat jar (without embedding dependencies) as well and mainly ensure this plain jar is deployed to maven central (version 3.6.0 is already deployed).
Indeed, i'm happy to announce that jmeld can be installed simply (as long as you continue to deploy flat jars) using this command (that works like a charm with the 3.6.0):
```sh
nuts install org.jmeld:jmeld
```
and later can be run 
```sh
nuts jmeld
```
`nuts` is actually a new java package manager we are working on (https://github.com/thevpc/nuts) that supports out of the box maven built packages

**Comment by albfan** [comment]
First, have to mention that I continue work from original project when it was on sourceforge. Original author retakes it on https://github.com/Mrkuip/jmeld, but I have several fixes related to VCS while he mostly migrates to javaFX. I was unable to port back my changes to his repo.

That said, jmeld plain jar is still released. Removing: 

```
diff --git i/pom.xml w/pom.xml
index 1b97d03..a503517 100644
--- i/pom.xml
+++ w/pom.xml
@@ -128,7 +128,6 @@
                 <artifactId>maven-jar-plugin</artifactId>
                 <version>2.6</version>
                 <configuration>
-                    <finalName>jmeld</finalName>
                     <archive>
                         <manifest>
                             <addClasspath>true</addClasspath>
```

will generate `jmeld-3.6.0.jar` instead of `jmeld.jar`

I'm glad you develop such application, but for people getting nuts trying to run a jar with dependencies, I don't think install another app to wrap that will fix it.

What about offine execution?

**Comment by thevpc** [comment]
Thanks for the reply.
However I'm convinced that a package manager is a better solution for deployment than fat jars:
* You won't install shared libraries twice (better disk management and better network management for the end user)
* One single command (or store app) to install whatever software
* Simple update management (always get the latest version)
* Centralized info on what you have installed on your system
* Offline mode (as a reply to your last question) is about using shared libraries that are stored offline, you won't have to be online after installing the software (the same applies to the jar with dependencies). The only use case I can think of, is that you want to share the app with a non connected machine, but again this is simply doable in `nuts`, you install on any connected machine, you backup the repository (simple zip), and you copy/import this repository to your non connected machine. It seems complicated but actually it's a simple backup/restore command.
* and most of all, the cost of having a `nuts` supported app is near to nothing : all maven packages are supported because `nuts` reuses maven `pom` descriptors.
