### ISSUE TITLE
How can I get RSyntaxTextArea to fill the size of it's parent container (eg: JPanel)

### ISSUE THREAD

**Issue by allmankind123** [albfan/jmeld#73]
the no-arg constructor doesnt do this and for  the rows/columns constructor, what is the algorithm to determine the correct width.
currently if I over specify the width and height, then I cannot see the scrollbars or components below.

**Comment by albfan** [comment]
I'm unsure if you can ask here general questions about a component jmeld uses.

Please expose what is the relation for this issue with jmeld to reopen
